### ISSUE TITLE
Подкаст

### ISSUE THREAD

**Issue by arRedFox** [learnjskiev/learning-resources#1]
http://radiojs.ru/  - подкаст суто по js
http://devzen.ru/ - про програмування в цілому і про веб технології зачасту

**Comment by arlekin12** [comment]
http://resrc.io/list/18/javascript-frameworks/
http://resrc.io/list/217/programming-interactive-tutorials/

**Comment by drKraken** [comment]
:+1:  щас додам

**Comment by drKraken** [comment]
d6f9dfcb7ca1656a688f5e8fe1d07ef0c13cf05c
