### ISSUE TITLE
Відеоуроки по веб-розробці

### ISSUE THREAD

**Issue by odayny** [learnjskiev/learning-resources#2]
https://www.youtube.com/user/loftblog/playlists

Розбито на плейлісти, в основному охоплюється Web-UI.

**Comment by drKraken** [comment]
Додав

**Comment by videvbat** [comment]
Привет. Спасибо за сообщение. Я немного выпал в последние два дня. Работы
много( увы.
На чем сейчас там остановились мы? что Делаем, какой план работы?

2015-02-25 23:39 GMT+02:00 Oleh Kuchuk <notifications@github.com>:
